export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const FETCH_ALL_INCIDENT_START = 'FETCH_ALL_INCIDENT_START';
export const FETCH_ALL_INCIDENT_SUCCESS = 'FETCH_ALL_INCIDENT_SUCCESS';
export const FETCH_ALL_INCIDENT_FAILURE = 'FETCH_ALL_INCIDENT_FAILURE';

export const CREATE_NEW_INCIDENT_START = 'CREATE_NEW_INCIDENT_START';
export const CREATE_NEW_INCIDENT_SUCCESS = 'CREATE_NEW_INCIDENT_SUCCESS';
export const CREATE_NEW_INCIDENT_FAILURE = 'CREATE_NEW_INCIDENT_FAILURE';

export const FETCH_SINGLE_INCIDENT_START = 'FETCH_SINGLE_INCIDENT_START';
export const FETCH_SINGLE_INCIDENT_SUCCESS = 'FETCH_SINGLE_INCIDENT_SUCCESS';
export const FETCH_SINGLE_INCIDENT_FAILURE = 'FETCH_SINGLE_INCIDENT_FAILURE';

export const FETCH_ALL_INTERVENTION_SUCCESS =
  'FETCH_SINGLE_INCIDENT_SUCCESS_INTERVENTIONS';
export const FETCH_ALL_INCIDENT_SUCCESS_REDFLAGS =
  'FETCH_SINGLE_INCIDENT_SUCCESS_REDFLAGS';
export const FETCH_ALL_REDFLAG_SUCCESS = 'FETCH_ALL_REDFLAG_SUCCESS';
