export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const FETCH_ALL_INCIDENT_START = 'FETCH_ALL_INCIDENT_START';
export const FETCH_ALL_INCIDENT_SUCCESS = 'FETCH_ALL_INCIDENT_SUCCESS';
export const FETCH_ALL_INCIDENT_FAILURE = 'FETCH_ALL_INCIDENT_FAILURE';

export const CREATE_NEW_INCIDENT_START = 'CREATE_NEW_INCIDENT_START';
export const CREATE_NEW_INCIDENT_SUCCESS = 'CREATE_NEW_INCIDENT_SUCCESS';
export const CREATE_NEW_INCIDENT_FAILURE = 'CREATE_NEW_INCIDENT_FAILURE';

export const FETCH_SINGLE_INCIDENT_START = 'FETCH_SINGLE_INCIDENT_START';
export const FETCH_SINGLE_INCIDENT_SUCCESS = 'FETCH_SINGLE_INCIDENT_SUCCESS';
export const FETCH_SINGLE_INCIDENT_FAILURE = 'FETCH_SINGLE_INCIDENT_FAILURE';

export const FETCH_ALL_INTERVENTION_SUCCESS =
  'FETCH_SINGLE_INCIDENT_SUCCESS_INTERVENTIONS';
export const FETCH_ALL_INCIDENT_SUCCESS_REDFLAGS =
  'FETCH_SINGLE_INCIDENT_SUCCESS_REDFLAGS';
export const FETCH_ALL_REDFLAG_SUCCESS = 'FETCH_ALL_REDFLAG_SUCCESS';

export const CURRENT_USER = 'CURRENT_USER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

export const EDIT_INCIDENT_START = 'EDIT_INCIDENT_START';
export const EDIT_INCIDENT_SUCCESS = 'EDIT_INCIDENT_SUCCESS';
export const EDIT_INCIDENT_FAILURE = 'EDIT_INCIDENT_FAILURE';

export const DELETE_INCIDENT_START = 'DELETE_INCIDENT_START';
export const DELETE_INCIDENT_SUCCESS = 'DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_FAILURE = 'DELETE_INCIDENT_FAILURE';
