export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const FETCH_INCIDENT_START = 'FETCH_INCIDENT_START';
export const FETCH_INCIDENT_SUCCESS = 'FETCH_INCIDENT_SUCCESS';
export const FETCH_INCIDENT_FAILURE = 'FETCH_INCIDENT_FAILURE';

export const CREATE_INCIDENT_START = 'CREATE_INCIDENT_START';
export const CREATE_INCIDENT_SUCCESS = 'CREATE_INCIDENT_SUCCESS';
export const CREATE_INCIDENT_FAILURE = 'CREATE_INCIDENT_SUCCESS';

export const UPLOAD_MEDIA_START = 'UPLOAD_MEDIA_START';
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS';
export const MEDIA_UPLOAD_RESET = 'MEDIA_UPLOAD_RESET';

export const FETCH_SINGLE_INCIDENT_START = 'FETCH_SINGLE_INCIDENT_START';
export const FETCH_SINGLE_INCIDENT_SUCCESS = 'FETCH_SINGLE_INCIDENT_SUCCESS';
export const FETCH_SINGLE_INCIDENT_FAILURE = 'FETCH_SINGLE_INCIDENT_FAILURE';
